[package]
name = "notification-service"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
futures-util = "0.3.30"
log = "0.4.21"
simple_logger = "4.3.3"
tokio = { version = "1.36.0", features = ["net", "full"] }
tokio-tungstenite = "0.21.0"
